### PR TITLE
[PDP-1082-DTI] Refactored `dti` feature to use only primitives

### PR DESCRIPTION
**Pull request by AdityaRao1996**
- Refactored `debt_to_income_ratio_latest` feature to make use of `/balances` and `/transactions` instead of resorting to credit-report
- Updated README accordingly

### CODE REVIEW

**Review by nickmasson — CHANGES_REQUESTED** [review]
can you rework this to make it more efficient? you can cut the number of API calls ~ in half, if you make a single call to collect all the records you need, and then segregate in memory.
--
nevermind. I see that we're pulling balances for loans. but transactions (credits) for depository.
You can still make this more efficient by not having two sequential blocking awaits. i.e. rework 
```
    balances_resp = await asyncio.gather(*loan_inst_coroutines)
    transactions_resp = await asyncio.gather(*depository_inst_coroutines)
```
to: 
```
resp = await asyncio.gather( *loan_inst_coroutines, *depository_inst_coroutines)
balances_resp = resp[len(loan_inst_coroutines):]
transactions_resp = resp[:len(loan_inst_coroutines) ]
```

Also suggest some better naming.
loan_balances
depository_transactions

prone to errors otherwise

**Comment by AdityaRao1996** [comment]
> can you rework this to make it more efficient? you can cut the number of API calls ~ in half, if you make a single call to collect all the records you need, and then segregate in memory.
> 
> ```
>         api_client.balances.get(
>             user_uuid=user_uuid,
>             institution_id=institution.institution_id,
>             utc_starttime=utc_starttime,
>             utc_endtime=utc_time,
>             account_types=["loan", "depository"],
>         )
>         for institution in institutions_w_loan_and_depository
>     ]
> ```

The second API call is for the `/transactions` endpoint (which is being filtered for depository accounts).
Could have definitely made one call and segregated in memory if we were using only `/balances` or only `/transactions` endpoint 😄

Please let me know if I've understood your comment correctly 🙇🏽‍♂️

**Comment by AdityaRao1996** [comment]
> ## can you rework this to make it more efficient? you can cut the number of API calls ~ in half, if you make a single call to collect all the records you need, and then segregate in memory.
> nevermind. I see that we're pulling balances for loans. but transactions (credits) for depository. You can still make this more efficient by not having two sequential blocking awaits. i.e. rework
> 
> ```
>     balances_resp = await asyncio.gather(*loan_inst_coroutines)
>     transactions_resp = await asyncio.gather(*depository_inst_coroutines)
> ```
> 
> to:
> 
> ```
> resp = await asyncio.gather( *loan_inst_coroutines, *depository_inst_coroutines)
> balances_resp = resp[len(loan_inst_coroutines):]
> transactions_resp = resp[:len(loan_inst_coroutines) ]
> ```
> 
> Also suggest some better naming. loan_balances depository_transactions
> 
> prone to errors otherwise

Yes, that sounds great! Just pushed the changes for ^^ 😄

**Review by nickmasson — APPROVED** [review]
lgtm. just make sure that the example values in the __main__ block still return a good example response. otherwise 🚢 🚀

**Comment by AdityaRao1996** [comment]
> lgtm. just make sure that the example values in the **main** block still return a good example response. otherwise 🚢 🚀

Yes ✅ It does 😄

**Pull request merged**
